dependencies = {
    layers:  [

		{
			//This layer will be discarded, it is just used
			//to specify some modules that should not be included
			//in a later layer, but something that should not be
			//saved as an actual layer output. The important property
			//is the "discard" property. If set to true, then the layer
			//will not be a saved layer in the release directory.
			name: "string.discard",
			resourceName: "string.discard",
			discard: true,
			//Path to the copyright file must be relative to
			//the util/buildscripts directory, or an absolute path.
			copyrightFile: "myCopyright.txt",
			dependencies: [
					"dojo.string"
			]
		},

		{
	        name: "../agua.js",
            dependencies: [
				"plugins.admin.Access",
				"dijit.dijit",
				"dijit.form.CheckBox",
				"dijit.form.ValidationTextBox",
				"dijit.form.RadioButton",
				"dijit.form.ComboBox",
				"dijit.form.Slider",
				"dijit.form.FilteringSelect",
				"dijit.form.Button",
				"dijit.form.NumberSpinner",
				"dijit.Editor",
				"dijit.form.DateTextBox",
				"dijit.form.Textarea",
				"dijit.form.TextBox",
				"dijit.form.NumberTextBox",
				"dijit.form.CurrencyTextBox",
				"dojo.currency",
				"dijit.Dialog",
				"dojo.data.ItemFileWriteStore",
				"dojox.grid.Grid",
				"dojo.parser",
				"dojox.grid._data.model",
				"plugins.core.form.Template",
				"plugins.admin.Admin",
				"dojo.dnd.Source",
				"dojo.dnd.Moveable",
				"dojo.dnd.Mover",
				"dojo.dnd.move",
				"dojo.data.ItemFileReadStore",
				"plugins.core.BorderContainer",
				"plugins.core.ExpandoPane",
				"plugins.admin.Parameters",
				"plugins.admin.Apps",
				"plugins.admin.Projects",
				"plugins.admin.GroupProjects",
				"plugins.admin.Users",
				"plugins.admin.GroupUsers",
				"plugins.admin.Sources",
				"plugins.admin.GroupSources",
				"plugins.admin.Groups",
				"plugins.core.Common",
				"plugins.admin.AppRow",
				"plugins.admin.ConfirmDialogue",
				"dojox.layout.FloatingPane",
				"dijit.TitlePane",
				"dijit.layout.TabContainer",
				"plugins.admin.Controller",
				"plugins.core.WidgetFramework",
				"plugins.core.ComboBox",
				"dijit.Tooltip",
				"plugins.admin.GroupProjectRow",
				"plugins.admin.GroupRow",
				"plugins.admin.GroupSourceRow",
				"plugins.admin.GroupUserRow",
				"plugins.admin.ParameterRow",
				"plugins.admin.ProjectRow",
				"plugins.admin.SourceRow",
				"dijit.Toolbar",
				"dojox.widget.Standby",
				"plugins.core.PluginManager",
				"dijit.layout.BorderContainer",
				"dojo.cookie",
				"plugins.core.BorderContainerStatic",
				"plugins.core.Controls",
				"dojox.layout.ResizeHandle",
				"dijit.layout.LayoutContainer",
				"plugins.core.DataManager",
				"plugins.core.DropTarget",
				"dojox.layout.ExpandoPane",
				"plugins.core.Plugin",
				"plugins.core.Test",
				"dijit.layout.AccordionContainer",
				"dijit.layout.ContentPane",
				"dijit.layout.SplitContainer",
				"plugins.dnd.Target",
				"plugins.files.Dialog",
				"dojox.widget.Dialog",
				"dojo.fx.easing",
				"dojox.timing.Sequence",
				"plugins.files.FileDrag",
				"dojox.widget.RollingList",
				"dojo.i18n",
				"plugins.files._GroupDragPane",
				"plugins.files.FileManager",
				"plugins.files.FileSelector",
				"dojox.data.FileStore",
				"dojox.widget.FileInput",
				"dojox.widget.FileInputAuto",
				"plugins.files.FileMenu",
				"plugins.menu.Menu",
				"plugins.core.InputDialog",
				"plugins.core.ConfirmDialog",
				"dojox.form.FileInputAuto",
				"plugins.files.FileSystem",
				"plugins.files.FolderMenu",
				"plugins.files.WorkflowMenu",
				"plugins.files.FileSelectorMenu",
				"dijit.Menu",
				"plugins.files.FileUpload",
				"dojox.form.FileInput",
				"dojox.form.FileUploader",
				"dojox.layout.ContentPane",
				"plugins.files.SelectorMenu",
				"plugins.files.TitlePane",
				"plugins.files.WorkflowSelectorMenu",
				"dijit.InlineEditBox",
				"dojo._base.fx",
				"dojo._base.html",
				"plugins.help.Controller",
				"plugins.help.Help",
				"includes.js",
				"dojox.widget.FisheyeLite",
				"plugins.admin.Login",
				"plugins.projects.Projects",
				"dojo.io.iframe",
				"dijit.form._FormWidget",
				"dijit._Templated",
				"dojox.widget.FilePicker",
				"dojo.dnd.Manager",
				"dojo.dnd.Selector",
				"plugins.project.Dialog",
				"plugins.project.Project",
				"plugins.project._GroupDragPane",
				"plugins.project.FileSelector",
				"plugins.project._GroupSelectorPane",
				"plugins.project.FileDrag",
				"plugins.report.Report",
				"plugins.view.View",
				"plugins.workflow.Workflow",
				"plugins.project.FileManager",
				"plugins.login.Controller"
				,
				"plugins.login.Login",
				"plugins.login.LoginStatus",
				"plugins.workflow.Controller",
				"plugins.project.Controller",
				"plugins.report.Controller",
				"plugins.project.API.EntrezAPI.EntrezAPI",
				"dojo._base.json",
				"dojo.collections.*",
				"plugins.report.Template",
				"plugins.project.FileInput",
				"plugins.project.FileInputAuto",
				"plugins.project.ProjectFiles",
				"plugins.project.SharedProjectFiles",
				"plugins.project.SourceFiles",
				"plugins.project.SharedSourceFiles",
				"plugins.report.Common",
				"plugins.report.Editor",
				"plugins.report.Grid",
				"dojox.grid.DataGrid",
				"plugins.report.SNP",
				"dijit.Tree",
				"dojox.rpc.Service",
				"dojo.io.script",
				"plugins.upload.FileUp",
				"plugins.upload.FileUpload",
				"dijit.ColorPalette",
				"plugins.workflow.FileManager",
				"plugins.workflow.FileSelector",
				"plugins.upload.FileInput",
				"plugins.workflow.Apps",
				"plugins.workflow.AppType",
				"plugins.workflow.AppRow",
				"plugins.workflow.AppsMenu",
				"plugins.workflow._GroupSelectorPane",
				"plugins.workflow.History",
				"plugins.workflow.HistoryRow",
				"plugins.workflow.HistoryPane",
				"plugins.workflow.HistoryPaneRow",
				"plugins.workflow.Parameters",
				"plugins.workflow.ParametersRow",
				"plugins.workflow.RunStatus",
				"plugins.workflow.Shared",
				"plugins.workflow.SharedRow",
				"plugins.workflow.Status",
				"dojox.timing",
				"plugins.workflow.Stages",
				"plugins.workflow.StageRow",
				"plugins.workflow.StagesMenu",
				"plugins.workflow.WorkflowIO",
				"plugins.core.Confirm",
				"plugins.workflow._GroupDragPane"

            ]
        }
    ]

	,

    prefixes: [
        [ "dijit", "../dijit" ],
        [ "dojox", "../dojox" ],
        [ "plugins", "../../plugins" ]
    ]
};